title: Centro Educativo Secundario RD
email: contacto@tu-escuela.edu.do
description: Formando líderes con valores y tecnología.
baseurl: "" 
url: "https://tu-usuario.github.io"

# Configuración de Colecciones para Personal
collections:
  personal:
    output: true
    permalink: /personal/:path/
