# Si su sitio es: https://jorgeabreu.github.io/centro-educativo/
# baseurl debe ser "/centro-educativo"
# Si es: https://jorgeabreu.github.io/
# baseurl debe ser ""

baseurl: "/centroeducativo" 
url: "https://jorge21028.github.io"
